name: Geocode wheel post commit steps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
         pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pylint src
      - name: Lint with flake8
        run : |
          flake8 --config=.flake8 src
      - name: Look for security issues with Bandit
        run: |
          bandit src
      - name: Type checking
        run: |
          mypy src
