name: Geocode wheel post commit steps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Tox
        run: |
          pip install tox
          tox
