name: Geocode wheel post commit steps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel pylint flake8 bandit mypy wheel typing
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pylint
        run: |
          pylint bcgeocoder
      - name: Lint with flake8
        run : |
          flake8 --config=.flake8 bcgeocoder
      - name: Look for security issues with Bandit
        run: |
          bandit bcgeocoder
      - name: Type checking
        run: |
          mypy bcgeocoder
